orchestration-api.service:
  endpoint: "https://digitalapi-stest.npe.auspost.com.au/"

api-gateway.service:
  endpoint: "https://digitalapi-stest.npe.auspost.com.au/"
  credentials:
    admin:
      username: health
      password: dontgopostal!!
    master:
      username: health
      password: dontgopostal!!

logging.level.org.paradise.net: DEBUG
