orchestration-api.service:
  endpoint: "https://digitalapi.paradise.net/"

api-gateway.service:
  endpoint: "https://digitalapi.paradise.net/"
  credentials:
    admin:
      username: health
      password: Somewhere over the rainbow way up high
    master:
      username: health
      password: Somewhere over the rainbow way up high

logging.level.org.paradise.net: DEBUG
