orchestration-api.service:
  endpoint: "http://localhost:8081/"

api-gateway.service:
  endpoint: "http://localhost:8081/"
  credentials:
    admin:
      username: health
      password: Somewhere over the rainbow way up high
    master:
      username: health
      password: Somewhere over the rainbow way up high

logging.level.org.paradise.net: DEBUG
